name: Deploy DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven Verify
      run: mvn -B clean verify
      
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
      
  deploy:
  
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: [docker]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy docker-compose to host
        uses: appleboy/scp-action@master
        with:
          # VPS IP
          host: ${{ secrets.AWS_HOST }}
             
          # VPS username
          username: ${{ secrets.AWS_USER }}
                  
          # SSH key (copy it from your local machine)
          key: ${{ secrets.AWS_KEY }}
          # SSH port
          port: ${{ secrets.AWS_PORT }}
          source: "docker-compose.yml,run.sh"
          target: "/var/tmp"
          
      - name: Change run permissions 
        uses: appleboy/ssh-action@master
        with:
          # VPS IP
          host: ${{ secrets.AWS_HOST }}
             
          # VPS username
          username: ${{ secrets.AWS_USER }}
                  
          # SSH key (copy it from your local machine)
          key: ${{ secrets.AWS_KEY }}
          # SSH port
          port: ${{ secrets.AWS_PORT }}
          script: |
            chmod +x /var/tmp/run.sh
      - name: Deploy app with webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: 
            ${{ format('http://{0}:9000/hooks/deploy}', secrets.AWS_HOST) }}




